from .env import (
    CporeEnv,
    AquaEnv,
    aqua_genome,
    aqua_genome_from_code,
    cell_genome_from_code,
    AQ_PART,
    AQ_PART_NAMES,
    AQ_GEN_BUDGET,
    AQ_STYLES,
    LandEnv,
    land_genome,
    land_genome_from_code,
    LAND_PART,
    LAND_PART_NAMES,
    LAND_GEN_BUDGET,
    LAND_STYLES,
    LAND_MAX_PARTS,
    LAND_PART_FIELDS,
    MEDIA,
    TribeEnv,
    TRIBE_STYLES,
    CivEnv,
    APPROACH,
    APPROACH_NAMES,
    SpaceEnv,
    SPACE_BONUSES,
    CporeVecEnv,
    make_gym_env,
    genome,
    PART,
    PART_NAMES,
    PART_COST,
    GEN_BUDGET,
    CELL_STYLES,
    STATUS,
    VIS,
    VIS_STYLES,
    LAND_VIS,
    DEFAULT_VIS,
    FRONT,
    RIGHT,
    BACK,
    LEFT,
)
try:
    # The vectorised envs need numpy, the one optional training dependency.
    # Everything else here is pure ctypes, so keep numpy optional end to end:
    # the studio and the raw envs must import on a box that only has libc.
    from .puffer import (
        CporePuffer,
        CellPuffer,
        AquaPuffer,
        LandPuffer,
        TribePuffer,
        CivPuffer,
        SpacePuffer,
        make_puffer_env,
    )
    _PUFFER_EXPORTS = ["CporePuffer", "CellPuffer", "AquaPuffer", "LandPuffer",
                       "TribePuffer", "CivPuffer", "SpacePuffer",
                       "make_puffer_env"]
except ImportError:                                    # pragma: no cover
    _PUFFER_EXPORTS = []
from .campaign import Campaign, STAGES
from .textgym import TextLand

__all__ = ["CporeEnv", "AquaEnv", "aqua_genome", "aqua_genome_from_code",
           "cell_genome_from_code",
           "LandEnv", "land_genome", "land_genome_from_code",
           "AQ_PART", "AQ_PART_NAMES", "AQ_GEN_BUDGET", "AQ_STYLES",
           "LAND_PART", "LAND_PART_NAMES", "LAND_GEN_BUDGET", "LAND_STYLES", "MEDIA",
           "LAND_MAX_PARTS", "LAND_PART_FIELDS",
           "TribeEnv", "TRIBE_STYLES",
           "CivEnv", "APPROACH", "APPROACH_NAMES",
           "SpaceEnv", "SPACE_BONUSES", "CporeVecEnv", "make_gym_env", "genome",
           "PART", "PART_NAMES", "PART_COST", "GEN_BUDGET", "CELL_STYLES", "STATUS",
           "VIS", "VIS_STYLES", "DEFAULT_VIS", "LAND_VIS",
           "FRONT", "RIGHT", "BACK", "LEFT",
           "Campaign", "STAGES", "TextLand"] + _PUFFER_EXPORTS
